/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bachamba;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Minh Tri
 */
public class SaveOpenFile extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public SaveOpenFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMa = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTen = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNgaySinh = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableDS = new javax.swing.JTable();
        btnMoFile = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thông Tin Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Mã Sinh Viên:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Tên Sinh Viên:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Ngày Sinh:");

        jScrollPane1.setViewportView(txtMa);

        jScrollPane2.setViewportView(txtTen);

        jScrollPane3.setViewportView(txtNgaySinh);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("(MM/dd/yyyy)");

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setText("LƯU");
        btnLuu.setEnabled(false);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setEnabled(false);
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setEnabled(false);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        TableDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sinh Viên", "Tên Sinh Viên", "Ngày Sinh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableDS);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );

        btnMoFile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMoFile.setText("Mở File");
        btnMoFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoFileMouseClicked(evt);
            }
        });

        btnLuuFile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLuuFile.setText("Lưu File");
        btnLuuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuFileMouseClicked(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoFile)
                        .addGap(33, 33, 33)
                        .addComponent(btnLuuFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoFile)
                    .addComponent(btnLuuFile)
                    .addComponent(btnThoat))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatMouseClicked
    private static int So_dong = 0;
    private static int So_cot = 0;
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        if(btnThem.getText().equals("THÊM"))
        {
            if(KiemTra.ThucHien_KT_Trong(txtMa.getText(), txtTen.getText(), txtNgaySinh.getText()) == true)
            {
                JOptionPane.showMessageDialog(null, "Mã Sinh Viên, Tên, Ngày Sinh không được để trống..!!!Vui lòng điền đầy đủ thông tin");
            }
            if(KiemTra.ThucHien_KT_Ngay(txtNgaySinh.getText()) == false) //  Kiem Tra Ngay Sinh
            {
                JOptionPane.showMessageDialog(null, "Ngày Sinh không đúng định dạng !!! Ví dụ: 9/29/1987");
            }
            else
            {
    //            String data[] = {txtMa.getText(), txtTen.getText(), txtNgaySinh.getText()};
                int lc = 1;
                for(int i = 0; i < So_dong-1; i++)
                {
                    Object o = TableDS.getValueAt(i, 0);
                    if(txtMa.getText().equals(o.toString()))
                    {
                        JOptionPane.showMessageDialog(null, "Mã sinh viên: "+txtMa.getText()+" này đã tồn tại bạn vui lòng nhập mã sinh viên khác");
                        lc = 0;
                    }
                }
                if(lc == 1)
                {
                    DefaultTableModel model =  (DefaultTableModel) TableDS.getModel();
                    model.addRow(new Object[]{txtMa.getText(), txtTen.getText(), txtNgaySinh.getText()});
                    btnLuu.setEnabled(true);
                    So_dong++;
                    So_cot++;
                    btnThem.setText("HỦY");
                }
            }
            
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
        else
        {
            txtMa.setText("");
            txtTen.setText("");
            txtNgaySinh.setText("");
            btnThem.setText("THÊM");
        }
        
    }//GEN-LAST:event_btnThemMouseClicked
    private static int row;
    private void TableDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSMouseClicked
        // TODO add your handling code here:
        btnSua.setEnabled(true);
        row = TableDS.getSelectedRow();      
        txtMa.setText(TableDS.getValueAt(row, 0).toString());
        txtTen.setText(TableDS.getValueAt(row, 1).toString());
        txtNgaySinh.setText(TableDS.getValueAt(row, 2).toString());
    }//GEN-LAST:event_TableDSMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        if(TableDS.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Bạn vui lòng chọn sinh viên trong danh sách sinh viên");
        }
        else
        {
            TableDS.setValueAt(txtMa.getText(), row, 0);
            TableDS.setValueAt(txtTen.getText(), row, 1);
            TableDS.setValueAt(txtNgaySinh.getText(), row, 2);
            
        }
        
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        if(TableDS.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Bạn vui lòng chọn sinh viên trong danh sách sinh viên");
        }
        else
        {
            Object[] options = { "+ Có +", "+ Không +" };
            int choice = JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn xóa sinh viên "+TableDS.getValueAt(row, 1).toString()+" này chứ ?", "Cảnh báo", WIDTH, HEIGHT, null, options, options[0]);
            if(choice == 0)
            {
                DefaultTableModel model =  (DefaultTableModel) TableDS.getModel();
                model.removeRow(row);
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnLuuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuFileMouseClicked
        // TODO add your handling code here:
        int choice = 0;
            while(choice == 0)
            {
        JFileChooser c = new JFileChooser();
        int rVal = c.showSaveDialog(null);
        if (rVal == JFileChooser.APPROVE_OPTION) 
        {
            
                String filename = c.getSelectedFile().getName();
                String dir = c.getCurrentDirectory().toString();

                java.io.File file = new java.io.File(dir+"\\"+filename+".txt");
                
                if(file.exists())
                {
                    Object[] options = { "+ OK +", "+ Cancel +" };
                    choice = JOptionPane.showOptionDialog(null, "File: "+filename+".txt đã tồn tại. Bạn có muốn ghi đè lên file này không","Cảnh báo", WIDTH, HEIGHT, null, options, options[0]);               
                }
                if(choice == 0)
                {
                    try 
                    {
                        file.createNewFile();
                    } 
                    catch (IOException ex) 
                    {
                        Logger.getLogger(SaveOpenFile.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    FileWriter writer; 
                    try 
                    {
                        writer = new FileWriter(file);
                        for(int i = 0; i < So_dong; i++)
                        {
                            //Object o = TableDS.getValueAt(i, 0);
                            writer.write(TableDS.getValueAt(i, 0).toString()+" ");
                            writer.write(TableDS.getValueAt(i, 1).toString()+" ");
                            writer.write(TableDS.getValueAt(i, 2).toString()+"\r\n");
                            
                        }
                        JOptionPane.showMessageDialog(null, "Ghi file: "+filename+".txt thành công !");
                        writer.flush();
                        writer.close();  
                        choice = 1;
                    } 
                    catch (IOException ex) 
                    {
                        Logger.getLogger(SaveOpenFile.class.getName()).log(Level.SEVERE, null, ex);
                    }           
                }
                else
                    choice = 0;
            }
            else
                c.setVisible(false);
        }        
    }//GEN-LAST:event_btnLuuFileMouseClicked

    private void btnMoFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoFileMouseClicked
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(null);
        
        if (rVal == JFileChooser.APPROVE_OPTION) 
        {
            String filename = c.getSelectedFile().getName();
            String dir = c.getCurrentDirectory().toString();
            //System.out.print(filename+" - "+dir);
            File file = new File(dir+"\\"+filename);
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(SaveOpenFile.class.getName()).log(Level.SEVERE, null, ex);
            }
            FileInputStream fis;
            try {
                fis = new FileInputStream(file);
                BufferedReader br = new BufferedReader(new InputStreamReader(fis));
                String line;

                while ((line = br.readLine()) != null) {
                    //
                    String rd[] = line.split(" ");
                    DefaultTableModel model =  (DefaultTableModel) TableDS.getModel();
                    model.addRow(new Object[]{rd[0], rd[1], rd[2]});
                    
                }     
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SaveOpenFile.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SaveOpenFile.class.getName()).log(Level.SEVERE, null, ex);
            }
                      
        }
       
        
    }//GEN-LAST:event_btnMoFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveOpenFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDS;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane txtMa;
    private javax.swing.JTextPane txtNgaySinh;
    private javax.swing.JTextPane txtTen;
    // End of variables declaration//GEN-END:variables
}
